#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import glob

translations = {
    'ShopVN': 'GlobalMart',
    'Mua sắm trực tuyến': 'Premium Online Shopping',
    'Nền tảng mua sắm trực tuyến hàng đầu Việt Nam. Hàng ngàn sản phẩm chính hãng, giao hàng nhanh, đổi trả dễ dàng.': 'Your premier online shopping destination. Thousands of authentic brand products with fast shipping and easy returns.',
    'mua sắm online, thương mại điện tử, shopvn, điện tử, thời trang, trang sức': 'online shopping, ecommerce, electronics, fashion, luxury brands, globalmart',
    'https://shopvn.example.com/': 'https://globalmart.example.com/',
    'Hàng ngàn sản phẩm chính hãng với giá tốt nhất. Giao hàng miễn phí cho đơn từ $50.': 'Thousands of authentic brand products with fast shipping and easy returns.',
    'https://ui-avatars.com/api/?name=ShopVN': 'https://ui-avatars.com/api/?name=GlobalMart',
    'Trang chủ': 'Home',
    'Sản phẩm': 'Products',
    'Danh mục': 'Categories',
    'Yêu thích': 'Wishlist',
    'So sánh': 'Compare',
    'Tìm kiếm sản phẩm...': 'Search products...',
    'Tất cả': 'All',
    'Tất cả sản phẩm': 'All Products',
    'Sản phẩm nổi bật': 'Featured Products',
    'Những sản phẩm được yêu thích nhất': 'Our most popular items',
    'Xem tất cả': 'View All',
    'Hàng mới về': 'New Arrivals',
    'Cập nhật liên tục mỗi ngày': 'Fresh additions daily',
    'Đã xem gần đây': 'Recently Viewed',
    'Tiếp tục khám phá những sản phẩm bạn quan tâm': 'Continue exploring what interests you',
    'Danh mục sản phẩm': 'Shop by Category',
    'Khám phá theo danh mục yêu thích': 'Explore our product categories',
    'Miễn phí vận chuyển': 'Free Shipping',
    'Cho đơn từ 500K': 'Orders over $50',
    'Hàng chính hãng': '100% Authentic',
    '100% đảm bảo': 'Guaranteed genuine',
    'Đổi trả dễ dàng': 'Easy Returns',
    'Trong vòng 30 ngày': '30-day policy',
    'Hỗ trợ 24/7': '24/7 Support',
    'Luôn sẵn sàng giúp đỡ': 'Always here to help',
    'Đăng ký nhận ưu đãi': 'Subscribe for Offers',
    'Nhận thông tin về sản phẩm mới và các chương trình khuyến mãi': 'Get updates on new products and exclusive deals',
    'Nhập email của bạn...': 'Enter your email...',
    'Đăng ký': 'Subscribe',
    'Mua sắm thông minh': 'Shop Smarter',
    'Hàng ngàn sản phẩm chính hãng với giá tốt nhất': 'Thousands of authentic brand products at the best prices',
    'Shop ngay': 'Shop Now',
    'Khám phá': 'Explore',
    'Thời trang xu hướng': 'Trending Fashion',
    'Cập nhật những xu hướng thời trang mới nhất': 'Latest trends from top global brands',
    'Xem bộ sưu tập': 'View Collection',
    'Điện tử cao cấp': 'Premium Electronics',
    'Công nghệ đỉnh cao cho cuộc sống hiện đại': 'Cutting-edge technology for modern living',
    'FLASH SALE đang diễn ra — Giảm đến 70%! Nhanh tay kẻo hết': 'FLASH SALE happening now — Up to 70% OFF! Hurry!',
    'Đang tải sản phẩm...': 'Loading products...',
    'Đang tải sản phẩm': 'Loading products',
    'Không tìm thấy sản phẩm nào': 'No products found',
    'Thử điều chỉnh bộ lọc hoặc từ khóa tìm kiếm': 'Try adjusting your filters or search terms',
    'Xóa bộ lọc': 'Clear Filters',
    'Xem': 'View',
    'Thêm': 'Add',
    'Thêm vào giỏ': 'Add to Cart',
    'Đã thêm vào danh sách yêu thích!': 'Added to wishlist!',
    'Đã xóa khỏi danh sách yêu thích.': 'Removed from wishlist.',
    'Thêm vào giỏ thành công!': 'Added to cart!',
    'Chi tiết sản phẩm': 'Product Details',
    'Mô tả': 'Description',
    'Đánh giá': 'Reviews',
    'Thông số kỹ thuật': 'Specifications',
    'Sản phẩm liên quan': 'Related Products',
    'Giỏ hàng của bạn': 'Your Cart',
    'Giỏ hàng trống': 'Your cart is empty',
    'Tiếp tục mua sắm': 'Continue Shopping',
    'Tạm tính': 'Subtotal',
    'Phí vận chuyển': 'Shipping',
    'Giảm giá': 'Discount',
    'Tổng cộng': 'Total',
    'Mã giảm giá': 'Coupon Code',
    'Áp dụng': 'Apply',
    'Thanh toán': 'Checkout',
    'Đặt hàng': 'Place Order',
    'Đang xử lý...': 'Processing...',
    'Đặt hàng thành công': 'Order placed successfully',
    'Mã đơn hàng': 'Order Code',
    'Cảm ơn bạn đã đặt hàng!': 'Thank you for your order!',
    'Thông tin tài khoản': 'Account Info',
    'Lịch sử đơn hàng': 'Order History',
    'Đơn hàng': 'Orders',
    'Trạng thái': 'Status',
    'Ngày đặt': 'Order Date',
    'Tổng tiền': 'Total',
    'Xem chi tiết': 'View Details',
    'Hủy đơn': 'Cancel Order',
    'Đã xác nhận': 'Confirmed',
    'Đang giao hàng': 'Shipping',
    'Đã giao hàng': 'Delivered',
    'Đã hủy': 'Cancelled',
    'Kết quả:': 'Results for:',
    'Tìm kiếm:': 'Search:',
    'Không thể tải sản phẩm.': 'Unable to load products.',
    'Kiểm tra kết nối mạng và thử lại.': 'Check your connection and try again.',
    'Thử lại': 'Retry',
    'Đăng ký thành công! Cảm ơn': 'Subscribed successfully! Thanks',
    'vào giỏ!': 'to cart!',
    'Tài khoản': 'Account',
    'Đăng nhập': 'Login',
    'Đăng xuất': 'Logout',
    'Đăng ký tài khoản mới': 'Create new account',
    'Email': 'Email',
    'Mật khẩu': 'Password',
    'Họ và tên': 'Full Name',
    'Địa chỉ': 'Address',
    'Số điện thoại': 'Phone',
    'Ngày sinh': 'Date of Birth',
    'Tạo tài khoản': 'Create Account',
    'Quên mật khẩu?': 'Forgot password?',
    'Chưa có tài khoản?': "Don't have an account?",
    'Đã có tài khoản?': 'Already have an account?',
    'Đổi mật khẩu': 'Change Password',
    'Cập nhật hồ sơ': 'Update Profile',
    'Hồ sơ cá nhân': 'Personal Profile',
    'Thông báo': 'Notifications',
    'Lưu thay đổi': 'Save Changes',
    'Hủy': 'Cancel',
    'Xác nhận': 'Confirm',
    'Tiếp tục': 'Continue',
    'Quay lại': 'Back',
    'Hoàn thành': 'Complete',
    'Lỗi': 'Error',
    'Thành công': 'Success',
    'Cảnh báo': 'Warning',
    'Thông tin': 'Info',
    'Về đầu trang': 'Back to top',
    'Giảm': 'Off',
    'Điện tử': 'Electronics',
    'Trang sức': 'Jewelry',
    'Thời trang Nam': "Men's Fashion",
    'Thời trang Nữ': "Women's Fashion",
    'Địa chỉ giao hàng mặc định': 'Default shipping address',
    'Cập nhật': 'Update',
    'Xóa': 'Delete',
    'Địa chỉ': 'Address',
    'Phương thức thanh toán': 'Payment Method',
    'Thêm địa chỉ mới': 'Add New Address',
    'Thêm thẻ mới': 'Add New Card',
    'Chỉnh sửa': 'Edit',
    'Đặt làm mặc định': 'Set as Default',
    'Ngày': 'Date',
    'Thao tác': 'Actions',
    'Chi tiết đơn hàng': 'Order Details',
    'Sản phẩm đã đặt': 'Products Ordered',
    'Tổng phụ': 'Subtotal',
    'Phương thức vận chuyển': 'Shipping Method',
    'Phương thức thanh toán': 'Payment Method',
    'Thông tin giao hàng': 'Shipping Info',
    'Ghi chú đơn hàng': 'Order Notes',
    'Đang xử lý': 'Processing',
    'Xác nhận đơn hàng': 'Confirm Order',
    'Theo dõi đơn hàng': 'Track Order',
    'Hỗ trợ khách hàng': 'Customer Support',
    'Câu hỏi thường gặp': 'FAQ',
    'Chính sách đổi trả': 'Return Policy',
    'Chính sách thanh toán': 'Payment Policy',
    'Về chúng tôi': 'About Us',
    'Liên hệ': 'Contact',
    'Hotline': 'Hotline',
    'Email hỗ trợ': 'Support Email',
    'Giờ làm việc': 'Working Hours',
    'Địa chỉ công ty': 'Company Address',
    'Kết nối với chúng tôi': 'Connect with Us',
    'Đăng ký bản tin': 'Newsletter',
    'Bản quyền': 'Copyright',
    'Mọi quyền được bảo lưu': 'All rights reserved',
    'Điều khoản sử dụng': 'Terms of Service',
    'Chính sách bảo mật': 'Privacy Policy',
    'Chính sách cookie': 'Cookie Policy',
    'Sản phẩm yêu thích': 'Favorite Products',
    'Danh sách so sánh': 'Compare List',
    'Thêm vào so sánh': 'Add to Compare',
    'Xóa khỏi so sánh': 'Remove from Compare',
    'So sánh sản phẩm': 'Compare Products',
    'Xóa tất cả': 'Clear All',
    'Không có sản phẩm nào': 'No products',
    'Thêm sản phẩm để so sánh': 'Add products to compare',
    'Giảm giá': 'Sale',
    'Hết hàng': 'Out of Stock',
    'Còn hàng': 'In Stock',
    'Sản phẩm mới': 'New',
    'Bán chạy': 'Best Seller',
    'Xem nhanh': 'Quick View',
    'Thêm vào wishlist': 'Add to Wishlist',
    'Xóa khỏi wishlist': 'Remove from Wishlist',
    'Sắp xếp theo': 'Sort by',
    'Giá: Thấp đến cao': 'Price: Low to High',
    'Giá: Cao đến thấp': 'Price: High to Low',
    'Đánh giá: Cao nhất': 'Rating: Highest',
    'Tên: A-Z': 'Name: A-Z',
    'Lọc': 'Filter',
    'Bộ lọc': 'Filters',
    'Xóa bộ lọc': 'Clear Filters',
    'Giá': 'Price',
    'Từ': 'From',
    'Đến': 'To',
    'Áp dụng bộ lọc': 'Apply Filters',
    'Đánh giá': 'Rating',
    'Từ': 'From',
    'sao trở lên': 'stars & up',
    'Lọc theo giá': 'Filter by price',
    'Lọc theo đánh giá': 'Filter by rating',
}

base_path = r"C:\Users\DMX\OneDrive\Máy tính\ShopVN\ecommerce"
html_files = glob.glob(os.path.join(base_path, "*.html"))

for filepath in html_files:
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        
        original = content
        for vi, en in translations.items():
            content = content.replace(vi, en)
        
        if content != original:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"Updated: {os.path.basename(filepath)}")
    except Exception as e:
        print(f"Error {filepath}: {e}")

# Also fix lang attribute
for filepath in html_files:
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        if 'lang="vi"' in content:
            content = content.replace('lang="vi"', 'lang="en"')
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"Fixed lang: {os.path.basename(filepath)}")
    except Exception as e:
        print(f"Error lang {filepath}: {e}")

print("Done!")
